# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FulaModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FulaModule
  pod 'Mobile','~> 0.0.3'
  pod "WnfsSwift",  '~> 0.1.6'
  pod 'CryptoSwift', '~> 1.7.1'
end
