# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FulaModule' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for FulaModule
  pod "Fula", '0.1.1'
  pod "WnfsSwift",  '~> 0.1.6'
  pod 'CryptoSwift', '~> 1.7.1'
end
