# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'FulaModule' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for FulaModule
  pod "Fula", '1.0.0'
  pod "Wnfs",  '~> 1.0.1'
  pod 'CryptoSwift', '~> 1.7.1'
end
